M48
; DRILL file {KiCad 7.0.7} date Sat Sep 23 00:26:50 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-23T00:26:50-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
%
G90
G05
T1
X6.1024Y-4.5276
T2
X5.5906Y-4.8425
X6.0906Y-4.8425
T3
X4.9347Y-4.7421
X4.9347Y-4.8421
T0
M30
